### ISSUE TITLE
Error: Carsim library is invalid

### ISSUE THREAD

**Issue by HuXingYu1016** [MizuhoAOKI/pycarsimlib#4]
How can I solve "Python size (32/64) must match size of .dlls being loaded. Python size: 64 DLL size: 32", thanks!

**Comment by MizuhoAOKI** [comment]
This library is just a wrapper to call the Carsim api. Also, please note that this is a privately developed software and not an official library.

Since your error is not printed out by my software, I cannot give you a precise answer to solve it. Unfortunately, I have not seen similar errors during development. It is also possible that the version of Carsim you are using is not compatible with my library. 

I suggest that you contact the official Carsim company with which you have a license agreement and inquire about the error.
